import re


def find_accounts(text):
    # QQ号正则表达式 (5-11位数字)
    qq_pattern = r'\b[1-9][0-9]{8,10}\b'

    # 中国大陆手机号正则表达式
    phone_pattern = r'\b1[3-9]\d{9}\b'

    # Telegram账号正则表达式 (@开头,4-32位字母、数字或下划线)
    # telegram_pattern = r'@[a-zA-Z0-9_]{4,32}\b'
    telegram_pattern = r'@\+?[a-zA-Z0-9_]{4,32}\b'

    # 查找所有匹配项
    qq_numbers = re.findall(qq_pattern, text)
    phone_numbers = re.findall(phone_pattern, text)
    telegram_accounts = re.findall(telegram_pattern, text)

    return {
        'qq_number': qq_numbers,
        'phone_number': phone_numbers,
        'telegram_number': telegram_accounts
    }


if __name__ == '__main__':

    # 测试代码
    test_text = """
NICHE Gold 420 X 型環鏈條114 鏈條附連接主鏈條Amazon.comhttps://www.amazon.com › zh_TW › NICHE-Gold-420...Amazon.comhttps://www.amazon.com › zh_TW › NICHE-Gold-420...X-Ring Drive Chain · Includes: NICHE Drive Chain · Compatible with the following brands: Honda, Yamaha · Compatible with the following models: RS100 ... 评分：4.5 · ‎540 条评价 · ‎US$29.95 · ‎现货tg kefuxiaokeai 420 china420 chinaweed icoDribbblehttps://dribbble.com › searchDribbblehttps://dribbble.com › search · 翻译此页Explore thousands of high-quality tg kefuxiaokeai 420 china420 chinaweed ico images on Dribbble. Your resource to get inspired, discover and connect with ...420 摩托車鏈420 標準滾子鏈132 鏈條420 驅動鏈適用於110 ...Amazon.comhttps://www.amazon.com › zh_TW › 標準滾子鏈-125c...Amazon.comhttps://www.amazon.com › zh_TW › 標準滾子鏈-125c...30 天免費更換420 鏈主鏈接! 無風險購買。因此請放心購買。真正無憂的購物體驗 ... 群準則。如果不符合，我們會將其移除。 檢舉. 取消. 抱歉，我們無法載入評論. 請 ... 评分：4.1 · ‎216 条评价 · ‎US$22.99联系群主购买TG电报（kefuxiaokeai）中国420+420中国+飞叶子 ...حراجhttps://haraj.com.sa › search › 联系群主购...حراجhttps://haraj.com.sa › search › 联系群主购... · 翻译此页联系群主购买TG电报（kefuxiaokeai）中国420+420中国+飞叶子+飞行燃料+CDC420+1.elv. لاتوجد اعلانات. Apple App Store Badge · Google Play Badge · Huawei App Store ...搜尋联系群主购买TG电报（kefuxiaokeai）中国420 ...今健康https://gooddoctorweb.com › search › tag今健康https://gooddoctorweb.com › search › tag · 转为简体网页搜尋联系群主购买TG电报（kefuxiaokeai）中国420+420中国+飞叶子+飞行燃料+CDC420+1.dnm. 搜尋結果0 筆數. 今健康New新聞. 早餐是開啟一天的最佳鬧鐘！「這三類」搭配缺一 ...联系群主购买TG电报|（kefuxiaokeai）飞叶子 420 中国大麻 ...ハマナカ手芸糸http://hamanaka.jp › s=联系群主购买TG电...ハマナカ手芸糸http://hamanaka.jp › s=联系群主购买TG电... · 翻译此页楽しい手芸のハマナカの商品情報サイトです。 人気の手あみ糸をはじめ、小ものやあみぐるみの手芸キット、フェルト羊毛、エコクラフトなど幅広く取り揃えております。联系群主购买TG电报|（kefuxiaokeai）飞叶子 420 中国大麻 ...Fahasa.comhttps://www.fahasa.com › search › q=联系群...Fahasa.comhttps://www.fahasa.com › search › q=联系群... · 翻译此页Kết quả tìm kiếm với: 联系群主购买TG电报|（kefuxiaokeai）飞叶子 420 中国大麻 china420 chinaweed,s7h. Không có sản phẩm phù hợp với từ khóa tìm kiếm của bạn.420 RuneCoins - RuneScape ®Steamhttps://store.steampowered.com › appSteamhttps://store.steampowered.com › app · 转为简体网页購買前請先確認語言支援清單。 可下載的內容. 您必須在Steam 上擁有遊戲主程式RuneScape ® 才能遊玩此內容。 購買RuneScape: 420 RuneCoins. $11.99. 加入購物車. 這項產品 ...US$11.99TS-420 | 硬件规格QNAP (中国)https://www.qnap.com.cn › ts-420 › specs › hardwareQNAP (中国)https://www.qnap.com.cn › ts-420 › specs › hardwareTS-420 Specification. TS-420. 规格信息. 特色 · 规格信息 · 扩充设备 · 兼容列表 · 下载中心. 购买→ ... 堆栈链结主装置: 最多8 个虚拟磁盘(通过iSCSI 启动器). 支持操作 ...小心！微信群里有些“团菜”信息可能是骗局澎湃新闻https://m.thepaper.cn › newsDetail_forward_19873196澎湃新闻https://m.thepaper.cn › newsDetail_forward_198731962022年9月12日 — 9月6日，家住花果园1期的池先生在业主群中看到团菜信息，赶忙下单购买 ... 在“团菜群”里，发起团购的群主发布了物资清单和金额，并要求大家用支付宝 ... |
| 湾区黄页爬山摄影群基本规范+搭车费用+免责声明湾区黄页爬山摄影群https://gohiking86.com › basic-rules湾区黄页爬山摄影群https://gohiking86.com › basic-rules... 420迈（含）的每人70元+过桥费+停车费。 8、往返超过420迈的， ... 加入我们的微信群及参加相关的所有活动，群员对自己的安全等全权负责，与群主或组织者毫无关系。玩Doubanhttps://m.douban.com › doulistDoubanhttps://m.douban.com › doulist购买前请注意有余额的时候会先用余额支付(谢谢7740uu的提醒) 避免爬... 汇报 ... 楼主是九个500人微信群群主，帮各位萌新解答所有疑问，也帮大家排雷，推... 说说 ...国家网信办:微信群等群主应履行群组管理责任Antpediahttps://wiki.antpedia.com › article-1424841-420Antpediahttps://wiki.antpedia.com › article-1424841-420... 主应履行群组管理责任, 国家互联网信息办公室7日印发《互联网群组信息服务管理规定》提出，互联网群组建立者、管理者应履行群 ... 购买食品发生纠纷，微信平台也要担责。对此 ...「联系群主购买TG电报|(kefuxiaokeai)飞叶子 420 中国大麻 ...ふるさとチョイスhttps://furusato-tax.jp › search › q=联系群主...ふるさとチョイスhttps://furusato-tax.jp › search › q=联系群主... · 翻译此页联系群主购买TG电报|(kefuxiaokeai)飞叶子 420 中国大麻 china420 chinaweed,J5aのお礼の品の検索ページはこちら。「ふるさとチョイス」ならフリーワードやカテゴリ ...請購買420 錘鈴圓頭鐵錘mceell 擺動健身錘核心肌群爆髮 ...露天市集https://www.ruten.com.tw › item › show露天市集https://www.ruten.com.tw › item › show · 转为简体网页規格: 4KG, 6KG..., 直購價: 1149 - 3714, 庫存: 99, 物品狀況: 全新,物品所在地: 台灣.台北市, 價格更新時間:, 上架時間: 2024-01-12, 分類: 生活居家> 家居主材> ...圆梦新媒体-第420章宅舞直播69书吧https://69shuba.cx › txt69书吧https://69shuba.cx › txt... 购买热情。 两个人聊着聊着都已经迷了进去，全然没有察觉旁边竟然多了沈易玲和包 ... 当中的一个主舞的女孩十分亮眼，非常明亮可爱，除了她娴熟的舞姿，还有她那 ...BIP-420正式提出OP_CAT操作码，引入比特币「契约」功能BlockBeatshttps://m.theblockbeats.info › flashBlockBeatshttps://m.theblockbeats.info › flash2024年4月23日 — ... 主爆多单. 47分钟前. DeepBrain Chain成功主办「去中心化AI的未来」峰会. 49分钟前. 美参议员将提出「由美国财政部在5年内购买100万枚比特币」提案. 在APP ...记者卧底揭露偷拍黑产后，多个偷拍群被禁言解散紫牛新闻https://www.yangtse.com › zncontent紫牛新闻https://www.yangtse.com › zncontent2021年12月27日 — “群主如果直接传播隐私信息，或者明知群里传播隐私信息，未尽到 ... 购买60台，420元可购买100台。价格越高，摄像头的位置就越来越私密、越来 ...自然语言处理产品如何计费,有哪些计费项_自然语言处理(NLP)阿里云文档https://help.aliyun.com › document_detail阿里云文档https://help.aliyun.com › document_detail主被叫意图识别. 累计500次. 疑似诈骗识别. 累计500次. 用户 ... 如需购买QPS增量服务，请加入“阿里云NLP基础服务2.0-用户答疑群”钉钉群号：35235845）咨询详细购买方案。SOUTH PARK: SNOW DAY! - 420 PackSteamhttps://store.steampowered.com › appSteamhttps://store.steampowered.com › app · 转为简体网页您必須在Steam 上擁有遊戲主程式SOUTH PARK: SNOW DAY! 才能遊玩此內容 ... 檢視更新歷史記錄 閱讀相關新聞 尋找社群群組. 名稱: SOUTH PARK: SNOW DAY! - 420 ... 平均评分：7/10 · ‎30 条评价 |
| BIP-420正式提出OP_CAT操作码，引入比特币「契约」功能BlockBeatshttps://m.theblockbeats.info › flashBlockBeatshttps://m.theblockbeats.info › flash2024年4月23日 — ... 主爆多单. 47分钟前. DeepBrain Chain成功主办「去中心化AI的未来」峰会. 49分钟前. 美参议员将提出「由美国财政部在5年内购买100万枚比特币」提案. 在APP ...有420亿美元该买什么？马斯克炫富网友疯狂抢答.....WENXUECITYhttps://www.wenxuecity.com › 新闻 › 焦点新闻WENXUECITYhttps://www.wenxuecity.com › 新闻 › 焦点新闻2024年5月22日 — 群吧 · 论坛 · 电台 · 焦点新闻 · 图片新闻 · 视频新闻 · 生活百态 · 娱乐新闻. advertisement. 您的位置： 文学城 » 新闻 » 焦点新闻 » 有420亿美元该买 ...撸毛必备，欧易子账号保姆级教程，一个账号生成420个充值 ...Mediumhttps://medium.com › 撸毛必备-欧易子账号保姆级教...Mediumhttps://medium.com › 撸毛必备-欧易子账号保姆级教...2023年3月30日 — OKX 有一个功能非常好用，每一个主账户可以生成20 个充值地址，如果你觉得不够用，那就开通子账户，每个账号最多开通20 个子账户。也就是说你开通一个OKX ...SOUTH PARK: SNOW DAY! - 420 PackSteamhttps://store.steampowered.com › appSteamhttps://store.steampowered.com › app · 转为简体网页您必須在Steam 上擁有遊戲主程式SOUTH PARK: SNOW DAY! 才能遊玩此內容 ... 檢視更新歷史記錄 閱讀相關新聞 尋找社群群組. 名稱: SOUTH PARK: SNOW DAY! - 420 ... 平均评分：7/10 · ‎30 条评价为什么狼群不敢攻击有牧羊犬的羊群？难道打不过一条狗？cnBeta.COMhttps://m.cnbeta.com.tw › viewcnBeta.COMhttps://m.cnbeta.com.tw › view18小时前 — ... 主通常愿意花大价钱购买5-7只牧羊犬来守护羊群的安全。 但即便如此，只要 ... 420 · Intel 13/14代不稳定微星率先发声：密切监视、8月中旬更新微码.群晖423+与420+区别抖音https://www.douyin.com › shipin抖音https://www.douyin.com › shipin2024年3月26日 — 如有群辉方案选型、购买问题欢迎随时私信我！ @ 群晖NAS存储-尹岳泉 · #群 ... 主中设置，其中速度权限我翻烂了，在其他地方都没有找到，我百度也 ...薅羊毛也有无间道：你以为的漏洞，很可能是营销黑猫投诉https://tousu.sina.cn › articles › view › 420黑猫投诉https://tousu.sina.cn › articles › view › 4202020年6月19日 — ... 群、拉人，都有相关的培训和统一话术。 其旗下买手分为VIP会员和运营商，运营商掌管着一个群，两者享有不同的佣金比例。 群主培训内容. 值得注意的是 ...充420元得500元话费？小心诈骗！ - 大连新闻大连新闻https://dalian.runsky.com › content_6239612大连新闻https://dalian.runsky.com › content_62396122024年4月22日 — 在群中有人指导小王做任务，第一个任务就是给指定的手机号码充值五百元 ... 第三步由此，诈骗分子便将诈骗赃款以充值话费的方式完成了“洗白”，购买 ...微信群网购抗原试剂，文山17人被骗！网易首页https://www.163.com › article网易首页https://www.163.com › article2023年1月1日 — 就加了对方微信购买了70支抗原试剂，她说她微信不能收款，让我用支付宝转账，我便将420元钱转入到了对方账户中。 ... 群主或管理员才能设置！ 科技小磊.文訊 10月號/2020 第420期 - 第 83 页 - Google 图书结果google.comhttps://books.google.com › booksgoogle.comhttps://books.google.com › books文訊編輯部 · 2020 · ‎History... 主動向主管要求轉調成為企畫,學習寫文案、辦活動與媒體溝通。有時間她甚至到「優 ... 群網站仍是她覺得最好的方式,大家會相信在臉書上說話的個人,例如今天請 ... |
| 《梵谷：尋光之路》特展 - udn售票網udn售票網https://tickets.udnfunlife.com › UTK02udn售票網https://tickets.udnfunlife.com › UTK02 · 转为简体网页... 主。若沒收到，請確認是否被郵件系統歸類到垃圾郵件）. 重發啟用信. 請輸入您的電子 ... 若您還不是會員，請先成為新會員。 綁定社群帳號. 忘記密碼. 重發啟用信. 09 ...韩束发力，利润最高预增3倍！上美股份却大跌6%Mitradehttps://www.mitrade.com › article-8-280606-20240729Mitradehttps://www.mitrade.com › article-8-280606-202407298小时前 — 除了主品牌韩束势能强劲，newpage ... 您并不实际拥有或持有任何相关基础资产。 Mitrade不提供任何关于购买、持有或出售差价合约的建议、推荐或意见。人民教师晒QNAP 威联通TS-420 NAS四盘位网络存储什么值得买https://post.smzdm.com › ...什么值得买https://post.smzdm.com › ...2014年5月5日 — 女王批复：“买个大的硬盘吧，将来存宝宝照片，硬盘钱我给你报了……”感动啊…… 不多说，进入正题——为啥买了这货：先是上网看了些品牌评测与比较，发现群晖 ...摄像头偷拍黑色产业链调查：一人洗澡百人“围观”人民日报-有品质的新闻https://www.peopleapp.com › article人民日报-有品质的新闻https://www.peopleapp.com › article2021年12月22日 — 在某聊天群中，有的卖家宣称只需花220元就可以购买并观看30台家庭对床、家庭厕所、SPA按摩店、更衣室、酒店的摄像头，320元可购买60台，420元可购买100台 ...线上麻将馆经“代理”拉人参赌牟利超千万，29名嫌疑人归案澎湃新闻https://m.thepaper.cn › newsDetail_forward_16612107澎湃新闻https://m.thepaper.cn › newsDetail_forward_166121072022年2月8日 — 吴林玩了一段时间，发现有许多赖账的玩家。后来他发现群主修改了“游戏规则”，只要打麻将就要向群主购买一定的分数，1元1分，群主拥有“计分权”，在游戏里 ...2020年寿光市惠农新农村建设投资开发有限公司绿色债券 ...中财网https://www.cfi.net.cn › ...中财网https://www.cfi.net.cn › ...8小时前 — ... 购买、出售、 持有任何证券的建议。本评级机构不对任何机构或个人因使用 ... 群、胶东经济圈建设的推进及交通基础设施的完善，寿光市面临较好的 ...14人合买彩票，花420元中640余万大奖无锡日报http://szb.wxrb.com › jnwb › content › content_99861无锡日报http://szb.wxrb.com › jnwb › content › content_998612021年11月16日 — “我一早起来，看到群里都快爆了”，中奖彩民“Jack”表示，看聊天记录才知道与人合买的号码中了大奖。这次合买的彩民以男性为主，只有两人是女的，其中一名女 ...毛泽东眼中的帝王将相 - Google 图书结果google.comhttps://books.google.com › booksgoogle.comhttps://books.google.com › books马银春 · 2013 · ‎Biography & Autobiography... 主姚泓为缓解两面受敌的危局,谋划先消灭沈田子军,再抵御刘裕,于是率步骑数万急趋 ... 群臣投降。九月刘裕率晋军浩浩荡荡地抵达皇城。他想在此稍作休整,经略关中 ...文訊 10月號/2020 第420期 - 第 83 页 - Google 图书结果google.comhttps://books.google.com › booksgoogle.comhttps://books.google.com › books文訊編輯部 · 2020 · ‎History... 主動向主管要求轉調成為企畫,學習寫文案、辦活動與媒體溝通。有時間她甚至到「優 ... 群網站仍是她覺得最好的方式,大家會相信在臉書上說話的個人,例如今天請 ...如何有效管理麻醉后的疼痛与不良反应？新浪财经https://finance.sina.cn › detail-imzknmas0194412.d.html新浪财经https://finance.sina.cn › detail-imzknmas0194412.d.html2023年9月4日 — 只要进行手术，就必定会做麻醉，以此抑制患者疼痛感知能力，有效降低患者进行手术时产生的痛苦，保证手术顺利开展，为患者手术安全提供基础保障。 |
| 【独家】“2023年中国大快消上市公司之日用品TOP15”揭晓！手机网易网https://www.163.com › article手机网易网https://www.163.com › article28分钟前 — ... 420余家大快消相关公司2023年业绩， ... 公司主营为表面活性剂、洗涤用品、其他业务，占比为87.2%、10.7 ...面積換算高雄市地政局https://landp.kcg.gov.tw › area高雄市地政局https://landp.kcg.gov.tw › area · 转为简体网页1平方公尺= 0.3025坪 · 1坪= 3.3058平方公尺 · 1公頃= 10000平方公尺= 3025坪= 1.03102甲 · 1甲= 10分= 2934坪= 0.96992公頃 · 1平方公里= 100公頃.乘車票價表統聯客運https://www.ubus.com.tw › FareInquiry統聯客運https://www.ubus.com.tw › FareInquiry · 转为简体网页※票價表為參考價，實際票價依現場為主. 國道路線. 路線名稱, 全票/ 優惠全票票價 ... 420元, 440元, 220元, -元, -元. 【1613】台北－屏東, 580元, 640元, 325元, -元, -元.3000亿元国家支持！四部门喊你领更新换新补贴 - 西安- 365淘房365淘房http://news.xa.house365.com › 西安房地产信息365淘房http://news.xa.house365.com › 西安房地产信息11小时前 — 比如，在汽车报废更新方面，对符合条件的汽车报废更新，将补贴标准由此前的购买 ... 再加上独立门厅入户、主卧套房，以及四房的配置，也能满足二孩 ...2024 台北101觀景台票價、優惠、介紹全攻略STAGE@TAIPEI 101https://stage.taipei101mall.com.tw › arti...STAGE@TAIPEI 101https://stage.taipei101mall.com.tw › arti... · 转为简体网页... 購買或線上購買套票。 Skyline 460 票種備註： 1.全程專人導覽，每天開放限定人數與固定預約場次15:00，實際時間依當天為主，如需包場其他時段可來電詢問。 2.Skyline ...第420章_靠八卦小报也能修仙60mi.comhttps://www.60mi.com › 4_420160mi.comhttps://www.60mi.com › 4_4201洛成当然清楚这些人为什么走的时候略显有些焦急，因为吴门主已死，三日内这群家伙中完全没有任何一个人和吴门主、在秘境之中取得过联系，无法确定吴门主此时的情况。Creative Cloud 定價和會籍計劃Adobehttps://www.adobe.com › plansAdobehttps://www.adobe.com › plans · 转为简体网页... 設計。 查看計劃和定價詳細資料. 加入 Adobe Stock 的 30 天免費試用。*. 安全交易. 立即購買. Acrobat Standard. NT$420/月. 年費計劃，14天內取消訂用可獲全額退款.尋光之路》25件真跡國際藝術展多元預售票只到8/23止| 藝開罐琅琅悅讀https://reading.udn.com › 琅琅悅讀 › 藝開罐 › 活動特區琅琅悅讀https://reading.udn.com › 琅琅悅讀 › 藝開罐 › 活動特區10小时前 — ... 主，如素描系列、《努南的舊塔樓》等作品。到1886年3月後，移居巴黎的梵 ... 群：FB、IG. 官方網站：https://uevent.udnfunlife.com ...多地启动配售型保障性住房意向登记工作销售均价约为市场价一半365淘房http://news.xa.house365.com › 西安房地产信息365淘房http://news.xa.house365.com › 西安房地产信息11小时前 — 刚刚，西安曝光420 ... 主，售价约为当前同区域商品住房售价的50%。 大连市配售型保障性住房轮候库也在近期宣布开放受理，相关要求包括，每个家庭只能购买 ...為奧運中華隊加油！泰山Cheers氣泡水攜手台北15間餐酒館酒訊https://ch-9.net › article酒訊https://ch-9.net › article · 转为简体网页3天前 — Cheers氣泡水更大方加碼，凡於社群指定貼文留言，還有機會免費把 ... 酒吧是以現代雞尾酒為主，提供高品質特色雞尾酒與多樣餐點料理，現代的 ... |
| 轉乘桃園機場統聯客運https://www.ubus.com.tw › index-T統聯客運https://www.ubus.com.tw › index-T · 转为简体网页※票價表為參考價，實際票價依現場為主. 轉乘桃園機場票價表. ※下列短區間請至各自營站現場購買. 區間, 全票, 半票. 桃園機場- 三條崙, 全票: 395+45=440 元, 半票: 190+20= ...台灣角川| #新書推薦#BL #漫畫試閱「我要解開你的詛咒。做 ...Instagramhttps://www.instagram.com › kadokawataiwan › PostInstagramhttps://www.instagram.com › kadokawataiwan › Post4天前 — 420滿額贈色紙（單款） 5000滿額贈色紙（整套） 900滿額贈提袋（艾莉款） 25週年特別滿額抽獎活動贈品 ⚠️贈品贈送狀況請依現場告知為主。 more. View ...《魔兽世界：地心之战》前夕版本游戏性改动一览旅法师营地https://www.iyingdi.com › post旅法师营地https://www.iyingdi.com › post主任务：能给予贵重游戏终局奖励的限时任务。 当地故事：能探索当地文化与支线 ... 群组管理器已更新，增加了新的动画和功能改进，包括：. 用于限制队友ping 的 ...中華職棒35年例行賽統一獅主場（下）ibon售票系統https://ticket.ibon.com.tw › Detailsibon售票系統https://ticket.ibon.com.tw › Details · 转为简体网页❺115cm以下兒童無需購票進場，但#不可佔座位。 ·高鐵國旅聯票優惠. ※ibon購買臺北大巨蛋、臺南棒球場 ...沖繩「那霸機場」必逛免稅店8選！酒、精品、伴手禮 - 完美行WAmazing Apphttps://tw.wamazing.com › articleWAmazing Apphttps://tw.wamazing.com › article · 转为简体网页8小时前 — 「Air BicCamera」隸屬於日本大型連鎖家電行「BicCamera」（ビックカメラ）旗下，販售商品以可帶上飛機或托運的中小型家電為主。從美顏儀、吹風機 ...南阳渡- 烟雨江湖WIKI_BWIKI哔哩哔哩游戏中心https://wiki.biligame.com › yanyu › 南阳渡哔哩哔哩游戏中心https://wiki.biligame.com › yanyu › 南阳渡【消灭狼群】. 南阳渡-伏牛山(51,29)：范大勇，打听【山洞】，选择【应下此事】 ... 如果主线做到贺庄主离开忘忧村将会无法触发该任务. 南阳渡(26,17)：触发剧情: 南阳 ...《魔兽世界》wlk珠宝加工专属宝石介绍九游https://www.9game.cn › moshoushijie2九游https://www.9game.cn › moshoushijie22天前 — ... 420：烈日石戒通过拍卖或者去商店中直接购买获得。 420~440：致密天蓝石 ... 玩家可以在孢子鱼群、纯净的水、高地杂鱼群等多个地方钓到，以下 ...上海祁连欣苑小区怎么样吉屋网https://sh.jiwu.com › loupan吉屋网https://sh.jiwu.com › loupan7天前 — 上海买房交流群-53群（482）. 加入群聊. 二手房源 全部房源 · 祁连欣苑2室2厅 ... 主卧朝南，小区中心位置，采光充足，中式风格 420万. 1室2厅丨67 ...Facebook怎么在群组发鐵TikTokhttps://www.tiktok.com › DiscoverTikTokhttps://www.tiktok.com › Discover... 购买12盒，直接帮你省下RM3XX ‼️  目前全马已经有1000++西药行和药材店都有售卖 ... 地魂归地府，到达地狱，因地魂可知主魂的一切之因果报应，也可指使在世肉身之 ...《魔兽世界》11.0地心之战前夕更新说明游民星空https://www.gamersky.com › handbook游民星空https://www.gamersky.com › handbook4天前 — 8 月1 日至8 月27 日，在全新的版本前夕事件中面对艾泽拉斯的记忆，并收集残存记忆来购买全新物品，好扩充你的战队收藏。 ... 适应虫群. 无尽虫群. |
| Facebook怎么在群组发鐵TikTokhttps://www.tiktok.com › DiscoverTikTokhttps://www.tiktok.com › Discover... 购买12盒，直接帮你省下RM3XX ‼️  目前全马已经有1000++西药行和药材店都有售卖 ... 地魂归地府，到达地狱，因地魂可知主魂的一切之因果报应，也可指使在世肉身之 ...《魔兽世界》11.0地心之战前夕更新说明游民星空https://www.gamersky.com › handbook游民星空https://www.gamersky.com › handbook4天前 — 8 月1 日至8 月27 日，在全新的版本前夕事件中面对艾泽拉斯的记忆，并收集残存记忆来购买全新物品，好扩充你的战队收藏。 ... 适应虫群. 无尽虫群.御汤山500平8居带300平花园南北向简装修随时签约房天下https://m.fang.com › esf › AGT_481117462房天下https://m.fang.com › esf › AGT_4811174622024/07/27. 留下出价更早获得房主反馈. 去出价. 房子降价了么？买哪儿才最赚？先来看看行情再说！ 购房不踩坑3000+人正在热聊. 加入群聊. 房源描述. 陈鹏评分：4.6TA ...省委部长楼一楼带80平私家花园特勤巡逻武警站岗房天下https://m.fang.com › esf › AGT_183911905房天下https://m.fang.com › esf › AGT_1839119051天前 — 本网站不声明或保证内容之正确性和可靠性，购买该房屋时，请谨慎核查。 ... 房主当前定价420万，出价可参考小区均价与房源核心卖点、业主心态等信息 ...新加坡移民指南新华乐https://www.anjiasg.com › singapore-immigration-guide新华乐https://www.anjiasg.com › singapore-immigration-guide5天前 — 成立并出售由风险投资支持或拥有创新技术的企业，需要提供相应的销售和购买协议等文件证明 ... 主都可以向该部门寻求帮助和建议。 该项计划的资格 ...魔兽世界wlk时光徽章价格怎么买划算魔兽世界时光徽章的机制九游https://www.9game.cn › moshoushijie2九游https://www.9game.cn › moshoushijie22天前 — 一、时光徽章涨跌机制给新人科普下，时光徽章是一种官方推出的虚拟物品，它允许玩家以游戏内的货币金币来交易游戏时间，或反之亦然，说白了就是可以 ...热门游戏- 3DMGAME论坛- Powered by Discuz!3DM论坛https://bbs.3dmgame.com › forum3DM论坛https://bbs.3dmgame.com › forum欢迎加入3DM怪物猎人世界联机群点击加入官方群：821044596: 版主: ごColdご, 你若喜欢怪人，, 望楉菡, 源啊圆 · 《模拟人生4》 (610): 模拟人生4专题站||优质整合包 ...大伙会跟亲友一起买周年演出票吗贴吧https://tieba.baidu.com › ...贴吧https://tieba.baidu.com › ...5小时前 — 剑网3吧. 关注826.2W 贴子369.4W 贴吧APP专享. Hm哥姐能不能别来主吧恶心人啊 ... 群到破防了，团内有人说觉得没啥问题。老二位置变了但没出现其他失误。老 ...盘点六星干员精一立绘贴吧https://tieba.baidu.com › ...贴吧https://tieba.baidu.com › ...1天前 — ... 群主cn：不晓得是circle name还是coser name的缩写总之就是你买谷用的昵称柄图：周边上印着的图。这次的音律的四张图就可以称作柄图通行证：明日方舟 ... 
"""
    results = find_accounts(test_text)
    for account_type, accounts in results.items():
        print(f"{account_type}: {accounts}")

# 号码转小写+去重复
